version: "3.8"

services:
  api:
    build: .
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes:
      - .:/app
      - ./wallet:/wallet
    ports:
      - "8000:8000"
    environment:
      - API_V1_STR=${API_V1_STR:-/api/v1}
      - SECRET_KEY=${SECRET_KEY:-q4qWC2K5mwT5BnNh0ZNF9MfeMDJenJ}
      - ALGORITHM=${ALGORITHM:-HS256}
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/bittensor_api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bittensor_api
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_CACHE_TTL=3600
      - TASK_STATUS_TTL=86400
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis
    restart: unless-stopped

  worker:
    build: .
    command: celery -A app.worker worker --loglevel=info
    volumes:
      - .:/app
      - ./wallet:/wallet
    environment:
      - API_V1_STR=${API_V1_STR:-/api/v1}
      - SECRET_KEY=${SECRET_KEY:-q4qWC2K5mwT5BnNh0ZNF9MfeMDJenJ}
      - ALGORITHM=${ALGORITHM:-HS256}
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/bittensor_api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bittensor_api
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_CACHE_TTL=3600
      - TASK_STATUS_TTL=86400
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - api
      - db
      - redis
    restart: unless-stopped

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bittensor_api
    restart: unless-stopped

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: